version: 2
jobs:
  build:
    docker:
      - {image: 'citusdata/extbuilder:latest'}
    steps:
      - {checkout: {path: src}}
      - {run: {name: 'Configure, Build, and Install', command: build-ext}}
      - {persist_to_workspace: {root: ., paths: [.]}}
  test-10/check-multi:
    docker:
      - {image: 'citusdata/exttester-10:latest'}
    working_directory: /home/circleci/project
    steps:
      - {attach_workspace: {at: .}}
      - {run: {name: 'Install and Test (check-multi)', command: 'install-and-test-ext check-multi'}}
  test-10/check-follower:
    docker:
      - {image: 'citusdata/exttester-10:latest'}
    working_directory: /home/circleci/project
    steps:
      - {attach_workspace: {at: .}}
      - {run: {name: 'Install and Test (check-follower)', command: 'install-and-test-ext check-follower-cluster'}}
  test-10/check-failure:
    docker:
      - {image: 'citusdata/failtester-10:latest'}
    working_directory: /home/circleci/project
    steps:
      - {attach_workspace: {at: .}}
      - {run: {name: 'Install and Test (check-failure)', command: 'install-and-test-ext check-failure'}}
  test-11/check-multi:
    docker:
      - {image: 'citusdata/exttester-11:latest'}
    working_directory: /home/circleci/project
    steps:
      - {attach_workspace: {at: .}}
      - {run: {name: 'Install and Test (check-multi)', command: 'install-and-test-ext check-multi'}}
  test-11/check-follower:
    docker:
      - {image: 'citusdata/exttester-11:latest'}
    working_directory: /home/circleci/project
    steps:
      - {attach_workspace: {at: .}}
      - {run: {name: 'Install and Test (check-follower)', command: 'install-and-test-ext check-follower-cluster'}}
  test-11/check-failure:
    docker:
      - {image: 'citusdata/failtester-11:latest'}
    working_directory: /home/circleci/project
    steps:
      - {attach_workspace: {at: .}}
      - {run: {name: 'Install and Test (check-failure)', command: 'install-and-test-ext check-failure'}}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - {test-10/check-multi: {requires: [build]}}
      - {test-10/check-follower: {requires: [build]}}
      - {test-10/check-failure: {requires: [build]}}
      - {test-11/check-multi: {requires: [build]}}
      - {test-11/check-follower: {requires: [build]}}
      - {test-11/check-failure: {requires: [build]}}
