version: 2
jobs:
  build:
    docker:
      - image: jasonmp85/citus-extbuilder:0.0.1
    steps:
      - checkout
      - run:
          name: Who am I?
          command: whoami
      - run:
          name: Where am I?
          command: pwd
      - run:
          name: What is here?
          command: ls
      - run:
          name: Where should I work?
          command: echo "${CIRCLE_WORKING_DIRECTORY}"
      # - persist_to_workspace:
      #     root: .
      #     # Must be relative path from root
      #     paths:
      #       - .
  # check-multi:
  #   docker:
  #     - image: jasonmp85/citus-builder:latest
  #   steps:
  #     - attach_workspace:
  #         # Must be absolute path or relative path from working_directory
  #         at: .
  #     - run:
  #         name: Install
  #         command: sudo make install --jobs=$(nproc)
  #     - run:
  #         name: Test
  #         command: make -C src/test/regress check-multi
  # check-tt-van-mx:
  #   docker:
  #     - image: jasonmp85/citus-builder:latest
  #   steps:
  #     - attach_workspace:
  #         # Must be absolute path or relative path from working_directory
  #         at: .
  #     - run:
  #         name: Install
  #         command: sudo make install --jobs=$(nproc)
  #     - run:
  #         name: Test
  #         command: make -C src/test/regress check-multi-task-tracker-extra check-vanilla check-multi-mx
  # check-iso-work-fol:
  #   docker:
  #     - image: jasonmp85/citus-builder:latest
  #   steps:
  #     - attach_workspace:
  #         # Must be absolute path or relative path from working_directory
  #         at: .
  #     - run:
  #         name: Install
  #         command: sudo make install --jobs=$(nproc)
  #     - run:
  #         name: Test
  #         command: make -C src/test/regress check-isolation check-worker check-follower-cluster
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - check-multi:
      #     requires:
      #       - build
      # - check-tt-van-mx:
      #     requires:
      #       - build
      # - check-iso-work-fol:
      #     requires:
      #       - build
