version: 2
jobs:
  build:
    docker:
      - image: jasonmp85/citus-builder:latest
    steps:
      - checkout
      - run:
          name: Configure
          command: mkdir build && cd build && ../citus/configure PG_CONFIG=/usr/lib/postgresql/11/bin/pg_config
      - run:
          name: Compile
          command: make --jobs=$(nproc)
      - run:
          name: Install
          command: make install --jobs=$(nproc)
      - run:
          name: Test
          command: make -C src/test/regress check-multi
